export const ADD_USERS = "ADD_USERS";
export const AUTHORIZATION = "AUTHORIZATION";
export const USERS_SET_IS_FETCHING = "USERS_SET_IS_FETCHING";
export const PROFILE_SET_IS_FETCHING = "PROFILE_SET_IS_FETCHING";
export const SET_PROFILE = "SET_PROFILE";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const CLEAR_PROFILE_HEADER_PHOTOS = "CLEAR_PROFILE_HEADER_PHOTOS";
export const PROFILE_SET_ERROR_MESSAGES = "PROFILE_SET_ERROR_MESSAGES";
export const SET_DIALOGS = "SET_DIALOGS";
export const SET_MESSAGES = "SET_MESSAGES";
export const CLEAN_MESSAGES = "CLEAN_MESSAGES";
export const BUTTON_SET_IS_FETCHING = "BUTTON_SET_IS_FETCHING";
export const SET_EDITE_MODE_PROFILE = "SET_EDITE_MODE_PROFILE";
export const SET_USERS_PAGE_PAGINATION = "SET_USERS_PAGE_PAGINATION";
export const SET_SELECTED_KEYS = "SET_SELECTED_KEYS";
export const SET_CURRENT_DIALOG = "SET_CURRENT_DIALOG";
export const CHANGE_PROFILE_PHOTO_SET_IS_FETCHING =
  "CHANGE_PROFILE_PHOTO_SET_IS_FETCHING";
